### ISSUE TITLE
Trying to figure out the syntax for a custom server list

### ISSUE THREAD

**Issue by TheFiZi** [Starbix/docker-synclounge#11]
I'm trying to pass this:

```
"servers": [
  {
    "name": "plexsync.fizi.ca",
    "location": "Cananananada",
    "url": "https://plexsync.fizi.ca/slserver",
    "logo": ""
  }
]
```

Into the `-servers=` parameter for the Docker container. I have tried dropping the `"servers": []` portion and including it 

I've tried these two commands:

`docker run -d --restart unless-stopped --name=SyncLounge -p 65500:8088 -p 65499:8089 -e DOMAIN=plexsync.fizi.ca -e servers=\"servers\":[{\"name\":\"plexsync.fizi.ca\",\"location\":\"Cananananada\",\"url\":\"https:\/\/plexsync.fizi.ca\/slserver\",\"logo\":\"\"}]" starbix/synclounge`

`docker run -d --restart unless-stopped --name=SyncLounge -p 65500:8088 -p 65499:8089 -e DOMAIN=plexsync.fizi.ca -e servers="{\"name\":\"plexsync.fizi.ca\",\"location\":\"Cananananada\",\"url\":\"https:\/\/plexsync.fizi.ca\/slserver\",\"logo\":\"\"}" starbix/synclounge`

Both result in a running docker container but this is what I get for a server list:

![Capture](https://user-images.githubusercontent.com/1762426/77716781-2be17a80-6f9c-11ea-9702-8a6afb934b00.PNG)

about 50 times.

How am I supposed to use this parameter properly?

**Comment by jwetzell** [comment]
I don't know if capitalization matters for docker ENV variables (I believe it does) but I have it like this and it works. No escaping quotes or anything

```
-e SERVERS='[{"name":"Server Name","location":"Server Location","url":"http://servurl.com/slserver","image":"http://loungeurl.com/flags/usa.png"}]'
```

**Comment by TheFiZi** [comment]
Thanks for the suggestion, interesting that `logo` is supposed to be `image`. Wonder where I got `logo` from.

I tried this with no luck. Same issue:

```
-e SERVERS='[{"name":"plexsync.fizi.ca","location":"Cananananada","url":"https://plexsync.fizi.ca/slserver","image":"https://fizi.ca/sheep.jpg"}]'
```

Wonder if it's having issues with SSL.

I'll just keep passing the settings.json into the container.
