### ISSUE TITLE
Nginx image does not work if webapp set to /

### ISSUE THREAD

**Issue by gravufo** [Starbix/docker-synclounge#4]
Currently, if I run the container with weboot='' and serverroot=/server, I get a blank page when going to http://<serverUrl>/. Checking my browser's dev tools' network section, it seems like it's trying to get some files from /slweb instead of just /.

I fixed it by manually rebuilding the webapp (npm run build), so I think the run.sh script is missing a rebuild when webroot=''.

I think the default configuration of the image should be / for webapp and /server for the server. Please consider changing it, since it makes more sense, especially for first time users like me that fall on a blank webpage and don't understand why :)

Let me know what you think!

Thanks

**Comment by gordogato** [comment]
honestly if you're running your own synclounge, there's a high chance you're also running a website/reverse proxy so the /slweb makes sense.

**Comment by gravufo** [comment]
I don't understand how your comment makes any difference to the initial problem. I am running it behind a reverse proxy already. What I am saying is that there should be something served to / by default and I am suggesting that it be the client. The server can still be served at /server.

I am currently running it this way (after some fiddling) and it works quite nicely/intuitively, so I don't see why this couldn't be done...

**Comment by gordogato** [comment]
Organizr requires apps have a webroot (/slweb) so for the majority of people it's the preferred config

**Comment by gordogato** [comment]
also it looks like v2 has / server root lol

**Comment by nwesthoff** [comment]
I'd also like to see a little more flexibility in terms of domain setup. I'm using [SteveLTN/https-portal](https://github.com/SteveLTN/https-portal) to reverse proxy all of my docker containers. I can't set different webroots for different containers. What I can do is set a subdomain though.

I was looking to create `synclounge.domain.com` and `slserver.domain.com` for it. Do you have a smart workaround maybe? :)

**Comment by gravufo** [comment]
This project is probably deprecated by the group watch feature in plex. Closing issue.
